export enum AdminPermission {
  READ = 'READ',
  MODIFY_FORM = 'MODIFY_FORM',
  DELETE_FORM = 'DELETE_FORM',
  ADD_FORM = 'ADD_FORM' ,
  LOCK_UNLOCK_USER = 'LOCK_UNLOCK_USER',
  GRANT_REVOKE_USER = 'GRANT_REVOKE_USER',
  DELETE_USER = 'DELETE_USER' ,
  MODIFY_USER = 'MODIFY_USER'
}



  
